config/routes.rb
Rails.application.routes.draw do
  resources :welcome_entries
  resources :galleries
  devise_for :admins
  root to: 'static#homepage'
end

app/models/admin.rb
class Admin < ApplicationRecord
	has_many :galleries
	has_many :welcome_entries
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	belongs_to :admin
	validates_presence_of :image

	mount_uploader :image, PhotoUploader
end

app/models/welcome_entry.rb
class WelcomeEntry < ApplicationRecord
	belongs_to :admin
	validates_presence_of :title, :description
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
	before_action :set_gallery, only: [:show, :edit, :update]
	before_action :authenticate_admin!

	def index
		@galleries = Gallery.all
	end

	def new
		@gallery = Gallery.new
	end

	def create
		@gallery = Gallery.new(gallery_params)
		@gallery.admin_id = current_admin.id

		if @gallery.save
			redirect_to root_path, notice: 'Foto Toegevoegd'
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if
			@gallery.update(gallery_params)
		  redirect_to galleries_path, notice: 'Foto gewijzigd!'
	  else
	  	render :edit
	  end
	end


	private

	  def gallery_params
	    params.require(:gallery).permit(:title, :image)
	  end

	  def set_gallery
	  	@gallery = Gallery.find(params[:id])
	  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
  	@galleries = Gallery.all
  end
end

app/controllers/welcome_entries_controller.rb
class WelcomeEntriesController < ApplicationController
	before_action :set_welcome_entry, only: [:show, :edit, :update]
	before_action :authenticate_admin!

	def index
		@welcome_entries = WelcomeEntry.all
	end

	def new
		@welcome_entry = WelcomeEntry.new
	end

	def create
		@welcome_entry = WelcomeEntry.new(welcome_entry_params)
		@welcome_entry.admin_id = current_admin.id

		if @welcome_entry.save
			redirect_to @welcome_entry, notice: "The details were created successfully"
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @welcome_entry.update(welcome_entry_params)
			redirect_to @welcome_entry, notice: 'The details were edited successfully'
		else
			render :edit
		end
	end

	private

		def welcome_entry_params
			params.require(:welcome_entry).permit(:title, :description)
		end

		def set_welcome_entry
			@welcome_entry = WelcomeEntry.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/welcome_entries_helper.rb
module WelcomeEntriesHelper
end

app/views/galleries/_form.html.erb
<div class="form">
	<%= form_for @gallery, class: "form-horizontal" do |f| %>

	  <% if @gallery.errors.any? %>
	    <% @gallery.errors.full_messages.each do |error| %>
	      <%= js add_gritter(error, title: "Hhhhhhmmmm..... iets is niet helemaal goed gegaan. Probeer het opnieuw of email me even!", sticky: false) %>
	    <% end %>
	  <% end %>
	  <h1>Wijzig foto</h1>
	  <br>
		<div class="form-group">
			<%= f.label :title, class: "col-sm-2 control-label" %>
			<%= f.text_field :title, class: "form-control" %>
		</div>

		<div class="form-group">
			
			<%= f.file_field :image %>
		</div>

	  <%= f.submit 'Bevestig wijziging', class: "btn btn-tendv " %>

	<%end %>
</div>

app/views/galleries/edit.html.erb
<%= render 'form' %>

app/views/galleries/index.html.erb
<% @galleries.each do |gallery| %> 
	<%# link_to edit_gallery_path(gallery) do %>
		<div class="gallery-index-wrap">
	  	<%= image_tag(gallery.image, class: "img-responsive gallery-index") %>
	  	<div class="gallery-index-middle">
				<%= link_to 'Wijzig Foto', edit_gallery_path(gallery), class: "gallery-index-text" %>
			</div>
	  </div>
	<%# end %>
<% end %>

app/views/galleries/new.html.erb
<h1>new</h1>

<%= form_for @gallery do |f| %>

  <%= f.text_field :title %>
  <%= f.file_field :image %>
  <%#= f.file_field :image %> 

  <%= f.submit 'Save' %>

<% end %>

app/views/galleries/show.html.erb
<%= @gallery.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tijger en de Vis</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-spy="scroll" data-target=".navbar" data-offset="50">

    <%= yield %>

    
    <!-- ============================= -->
    <!-- All your JavaScript comes now -->
    <!-- ============================= -->


    <%= javascript_include_tag "today", "data-turbolinks-track" => true  %>

    <%= js add_gritter(flash[:notice], title: "Tijger en de Vis", sticky: false, time: 3000) %>

    
    <script type="text/javascript">
      function initMap() {
        var tijgerEnDeVis = {lat: 52.380229, lng: 4.884260};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 19,
          center: tijgerEnDeVis
        });
        var marker = new google.maps.Marker({
          position: tijgerEnDeVis,
          map: map
          // animation: google.maps.Animation.BOUNCE
        });
      }
    </script>

    <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{ENV['GOOGLE_API_KEY']}&callback=initMap" %>

    <%= javascript_include_tag(:application) %>
  </body>
</html>

app/views/welcome_entries/_form.html.erb
<%= form_for @welcome_entry do |f| %>

  <%= f.text_field :title %>
  <%= f.text_area :description %>

  <%= f.submit 'Save' %>

<% end %>

app/views/welcome_entries/_welcome_entry.html.erb
<% @welcome_entries.each do |welcome_entry| %>
	<div class="well">
		<%= welcome_entry.title %>
	</div>
	<hr>
	<div class="well">
		<%= welcome_entry.description %>
	</div>
	<%= link_to 'Wijzig', edit_welcome_entry_path(welcome_entry), id: "edit_#{welcome_entry.id}" %>
<% end %>

app/views/welcome_entries/edit.html.erb
<h1>Wijzig</h1>
<%= render 'form' %>

app/views/welcome_entries/index.html.erb
<div class="wrapper">
	<%= render @welcome_entries %>
</div>

app/views/welcome_entries/new.html.erb
<%= form_for @welcome_entry do |f| %>

  <%= f.text_field :title %>
  <%= f.text_area :description %>

  <%= f.submit 'Save' %>

<% end %>

app/views/welcome_entries/show.html.erb
<%= @welcome_entry.inspect %>